---
- name: Check if npm 2.x is installed on the system.
  shell: $SHELL -lc "npm -v | grep -e '^2\.'"
  register: npm_installed
  changed_when: false
  ignore_errors: yes
  tags:
    - npm

- name: Install curl
  apt: name=curl state=present

- name: Install npm
  shell: $SHELL -lc "curl -L https://npmjs.com/install.sh | sh"
  when: npm_installed|failed
  tags:
    - npm

- name: Install global npm_packages
  npm: name={{ item.name | default(omit) }} path={{ item.path | default(omit) }} version={{ item.version | default(omit) }} global=yes state={{ item.state | default(omit) }}
  with_items: npm_packages
  tags:
    - npm
