---
- name: Ensure the latest node is installed
  apt: name=nodejs state=latest
  tags:
    - node

- name: Check if npm 2.x is installed on the system.
  shell: npm -v
  register: npm_version
  changed_when: false
  ignore_errors: yes
  tags:
    - node
    - npm

- name: Install curl
  apt: name=curl state=present
  when: npm_version.stdout | version_compare('2', '<')
  tags:
    - node
    - npm

- name: Install npm
  shell: $SHELL -lc "curl -L https://npmjs.com/install.sh | sh"
  when: npm_version.stdout | version_compare('2', '<')
  tags:
    - node
    - npm

- name: Install global npm_packages
  npm: name={{ item.name | default(omit) }} path={{ item.path | default(omit) }} version={{ item.version | default(omit) }} global=yes state={{ item.state | default(omit) }}
  with_items: npm_packages
  tags:
    - node
    - npm
